name: CI

on: [push, pull_request]

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - name: Test
        run: ./mvnw $MAVEN_ARGS verify

  javadoc:

    name: Javadoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - name: Generate Javadoc
        run: ./mvnw $MAVEN_ARGS -DskipTests package javadoc:javadoc

  sonar:

    name: Sonar code analysis
    runs-on: ubuntu-latest
    if: github.repository == 'assertj/assertj-assertions-generator' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'maven'
      - name: Test with Sonar
        run: >
          ./mvnw -V --no-transfer-progress -e clean verify javadoc:javadoc
          org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=assertj
          -Dsonar.projectKey=assertj_assertj-assertions-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-snapshot:

    name: Publish Snapshot
    needs: [test, javadoc]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'assertj' && github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Maven Central
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'zulu'
          java-version: '25'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: ./mvnw $MAVEN_ARGS -DskipTests -Ppublish deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
